// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmcvbmhfzseogmujxnxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtY3ZibWhmenNlb2dtdWp4bnhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjY0MTksImV4cCI6MjA1Nzk0MjQxOX0.7R8Cm8eKejxA7Eo8c2INoehWf1hCCAYkjZddKWHVTV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);